package com.campushub.service.impl;

import com.campushub.dto.ClubDto;
import com.campushub.dto.EventDto;
import com.campushub.entity.Club;
import com.campushub.entity.Event;
import com.campushub.entity.User;
import com.campushub.exception.ResourceNotFoundException;
import com.campushub.repository.ClubRepository;
import com.campushub.repository.EventRepository;
import com.campushub.repository.UserRepository;
import com.campushub.service.EventService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Implementation of EventService.
 */
@Service
public class EventServiceImpl implements EventService {

    @Autowired
    private EventRepository eventRepository;

    // needed because EventDto carries clubId/createdById, while the Event
    // entity holds Club and User references
    @Autowired
    private ClubRepository clubRepository;

    @Autowired
    private UserRepository userRepository;

    @Override
    @Transactional(readOnly = true)
    public List<EventDto> getAllEvents() {
        return eventRepository.findAll()
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Sorted by name because this feeds a dropdown - insertion order would look
     * arbitrary to whoever is filling in the form.
     */
    @Override
    @Transactional(readOnly = true)
    public List<ClubDto> getClubOptions() {
        return clubRepository.findAll(Sort.by(Sort.Direction.ASC, "name"))
                .stream()
                .map(this::toClubDto)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public EventDto getEventById(Long id) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Event not found with id: " + id));

        return toDto(event);
    }

    @Override
    @Transactional
    public EventDto createEvent(EventDto eventDto) {
        Event event = new Event();

        // the id is generated by the database and is never taken from the
        // request body, so a client cannot choose its own primary key
        event.setTitle(requireTitle(eventDto.getTitle()));
        event.setDescription(eventDto.getDescription());
        event.setEventDate(eventDto.getEventDate());
        event.setLocation(eventDto.getLocation());
        event.setClub(resolveClub(eventDto.getClubId()));
        event.setCreatedBy(resolveCreatedBy(eventDto.getCreatedById()));

        return toDto(eventRepository.save(event));
    }

    /**
     * Partial update: only the fields present in the request are applied, so an
     * edit form that sends just one field cannot erase the others. A field that
     * is absent from the JSON arrives as null and is therefore skipped, which
     * also means a value cannot be cleared back to null through this endpoint.
     */
    @Override
    @Transactional
    public EventDto updateEvent(Long id, EventDto eventDto) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Event not found with id: " + id));

        if (eventDto.getTitle() != null) {
            event.setTitle(requireTitle(eventDto.getTitle()));
        }

        if (eventDto.getDescription() != null) {
            event.setDescription(eventDto.getDescription());
        }

        if (eventDto.getEventDate() != null) {
            event.setEventDate(eventDto.getEventDate());
        }

        if (eventDto.getLocation() != null) {
            event.setLocation(eventDto.getLocation());
        }

        if (eventDto.getClubId() != null) {
            event.setClub(resolveClub(eventDto.getClubId()));
        }

        if (eventDto.getCreatedById() != null) {
            event.setCreatedBy(resolveCreatedBy(eventDto.getCreatedById()));
        }

        // the id in the body is ignored - the path variable identifies the event
        return toDto(eventRepository.save(event));
    }

    /**
     * Deletes the event and, by way of the ON DELETE CASCADE foreign keys in
     * schema.sql, its registrations and feedback along with it.
     *
     * The cascade is a deliberate team decision rather than an oversight: the
     * alternative was refusing to delete events that still have registrations.
     * Members 5 and 6 should be aware that this removes their rows too.
     */
    @Override
    @Transactional
    public void deleteEvent(Long id) {
        Event event = eventRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Event not found with id: " + id));

        eventRepository.delete(event);
    }

    /**
     * Maps an Event entity to its DTO.
     *
     * Only the identifiers of club/createdBy are read. Hibernate keeps the id on
     * the lazy proxy, so this does not trigger an extra query per event and is
     * safe outside an initialized session.
     */
    private EventDto toDto(Event event) {
        EventDto dto = new EventDto();
        dto.setId(event.getId());
        dto.setTitle(event.getTitle());
        dto.setDescription(event.getDescription());
        dto.setEventDate(event.getEventDate());
        dto.setLocation(event.getLocation());
        dto.setClubId(event.getClub() != null ? event.getClub().getId() : null);
        dto.setCreatedById(event.getCreatedBy() != null ? event.getCreatedBy().getId() : null);
        return dto;
    }

    /**
     * Maps a Club entity to Member 3's ClubDto. Only reads the createdBy id,
     * which Hibernate keeps on the lazy proxy, so no extra query per club.
     */
    private ClubDto toClubDto(Club club) {
        ClubDto dto = new ClubDto();
        dto.setId(club.getId());
        dto.setName(club.getName());
        dto.setDescription(club.getDescription());
        dto.setCreatedById(club.getCreatedBy() != null ? club.getCreatedBy().getId() : null);
        return dto;
    }

    /**
     * events.title is NOT NULL, so an empty title is rejected here instead of
     * being left to fail as a database constraint violation.
     */
    private String requireTitle(String title) {
        if (title == null || title.isBlank()) {
            throw new ResourceNotFoundException("title is required and cannot be blank");
        }

        return title;
    }

    /**
     * Every event must belong to a club (events.club_id is NOT NULL). Resolving
     * it here means an unknown clubId produces a clear 404 rather than a
     * constraint violation that the global handler would report as a 500.
     */
    private Club resolveClub(Long clubId) {
        if (clubId == null) {
            throw new ResourceNotFoundException("clubId is required - every event must belong to a club");
        }

        return clubRepository.findById(clubId)
                .orElseThrow(() -> new ResourceNotFoundException("Club not found with id: " + clubId));
    }

    /**
     * createdBy is optional - events.created_by is nullable - but if an id is
     * supplied it has to point at a real user.
     */
    private User resolveCreatedBy(Long userId) {
        if (userId == null) {
            return null;
        }

        return userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with id: " + userId));
    }
}
